"""empty message

Revision ID: 82223504c928
Revises: 
Create Date: 2018-10-11 19:51:22.227770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82223504c928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    op.drop_table('policy')
    op.drop_table('demand')
    op.drop_constraint('userfk', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('userfk', 'user', 'company', ['company_user'], ['name_company'], onupdate='CASCADE')
    op.create_table('demand',
    sa.Column('id_demand', mysql.INTEGER(display_width=255), autoincrement=True, nullable=False),
    sa.Column('company_demand', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('filler_demand', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_demand', mysql.TEXT(), nullable=False),
    sa.Column('detail_demand', mysql.TEXT(), nullable=True),
    sa.Column('domain_demand', mysql.TEXT(), nullable=True),
    sa.Column('type_demand', mysql.INTEGER(display_width=255), autoincrement=False, nullable=False),
    sa.Column('delete_demand', mysql.INTEGER(display_width=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['filler_demand'], ['user.phone_user'], name='demandfk'),
    sa.PrimaryKeyConstraint('id_demand'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('policy',
    sa.Column('id_policy', mysql.INTEGER(display_width=255), autoincrement=True, nullable=False),
    sa.Column('title_policy', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_policy', mysql.TEXT(), nullable=False),
    sa.Column('time_policy', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id_policy'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('company',
    sa.Column('code_company', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name_company', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('scope_company', mysql.TEXT(), nullable=True),
    sa.Column('industry_company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stuffnum_company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('registeredcaptial_company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('createdtime_company', sa.DATE(), nullable=True),
    sa.Column('contactname_company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contactphone_company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address_company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('partner_company', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('code_company'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    # ### end Alembic commands ###
